### PR TITLE
fix: refactor camelCase method

### LINKED ISSUE #462: ArrayIndexOutOfBoundsException when non alphanumeric String for camelCase method
The Strings.camelCase method is throwing a ArrayIndexOutOfBoundsException when it receives a non alphanumeric String like for example `__`:

For reproducing, look this [#464](https://github.com/halkyonio/primaza-poc/issues/464)

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
    at io.sundr.utils.Strings.camelCase (Strings.java:258)
    at io.sundr.builder.internal.checks.DublicatePropertyCheck.visit (DublicatePropertyCheck.java:19)
    at io.sundr.builder.internal.checks.DublicatePropertyCheck.visit (DublicatePropertyCheck.java:11)
    at io.sundr.builder.Visitor.visit (Visitor.java:30)
    at io.sundr.builder.VisitorWiretap.visit (VisitorWiretap.java:79)
    at io.sundr.builder.Visitable.accept (Visitable.java:67)
    at io.sundr.builder.Visitable.lambda$accept$1 (Visitable.java:81)
    at java.util.Optional.ifPresent (Optional.java:178)
    at io.sundr.builder.Visitable.accept (Visitable.java:73)
    at io.sundr.builder.Visitable.accept (Visitable.java:53)
    at io.sundr.builder.Visitable.accept (Visitable.java:30)
    at io.sundr.builder.internal.processor.BuildableProcessor.process (BuildableProcessor.java:82)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor (JavacProcessingEnvironment.java:1021)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs (JavacProcessingEnvironment.java:937)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run (JavacProcessingEnvironment.java:1265)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing (JavacProcessingEnvironment.java:1380)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations (JavaCompiler.java:1272)
    at com.sun.tools.javac.main.JavaCompiler.compile (JavaCompiler.java:946)
    at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0 (JavacTaskImpl.java:104)
    at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper (JavacTaskImpl.java:152)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall (JavacTaskImpl.java:100)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:94)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess (JavaxToolsCompiler.java:136)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile (JavacCompiler.java:183)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1140)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:193)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

### PR DESCRIPTION
**Pull request by aureamunoz**
Protect method for null, empty and non-alphanumeric Strings. Added test

Fixes #462

### CODE REVIEW

File: core/src/main/java/io/sundr/utils/Strings.java [hunk 1]
```diff
@@ -248,18 +248,48 @@ public static final String toFieldName(String name) {
...
+    } else if (name.isEmpty() || name.trim().isEmpty()) {
+      return "";
+    }
     String[] parts = name.split("[^a-zA-Z0-9]");
-    return parts[0] + Stream.of(parts)
-        .skip(1)
-        .filter(s -> s != null && s.length() > 0)
-        .map(v -> Character.toUpperCase(v.charAt(0)) + v.substring(1))
-        .collect(Collectors.joining());
+    if (parts.length > 0) {
```
Comment (iocanel) [inline core/src/main/java/io/sundr/utils/Strings.java:283]: I think that we don't really need this check as split will always return an array with at least 1 element.

File: core/src/main/java/io/sundr/utils/Strings.java [hunk 2]
```diff
@@ -248,18 +248,48 @@ public static final String toFieldName(String name) {
...
+   * }</pre>
+   *
+   * @param name the string to convert to camelCase
+   * @return the input string converted to camelCase format, or {@code null} if the input string is {@code null},
+   *         or an empty string if the input string is empty or contains only non-alphanumeric characters
    */
   public static final String camelCase(String name) {
+    if (name == null) {
+      return null;
+    } else if (name.isEmpty() || name.trim().isEmpty()) {
```
Comment (iocanel) [inline core/src/main/java/io/sundr/utils/Strings.java:279]: Optional: You may want to use our internal Strings.isNotNullOrEmpty instead.

**Review by iocanel — CHANGES_REQUESTED** [review]
Thanks, it looks great.
I think however that there is an if check that is not really needed and could be removed.

File: core/src/main/java/io/sundr/utils/Strings.java (hunk 1 above)
Comment (aureamunoz) [reply core/src/main/java/io/sundr/utils/Strings.java:283]: mmmmm, no. I've just checked to be sure. In case that the string doesn't match at all with the regex the result is an empty array and have an IndexOutOfBoundsException then.

File: core/src/main/java/io/sundr/utils/Strings.java (hunk 2 above)
Comment (aureamunoz) [reply core/src/main/java/io/sundr/utils/Strings.java:279]: I prefere not to return a different result depending on the input (null/empty).

File: core/src/main/java/io/sundr/utils/Strings.java (hunk 1 above)
Comment (iocanel) [reply core/src/main/java/io/sundr/utils/Strings.java:283]: ok

**Review by iocanel — APPROVED** [review]
lgtm

**Comment by aureamunoz** [comment]
I had to refactor more because CI was complaining

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by iocanel** [comment]
@aureamunoz: the downstream check fails, but let me run it against main to see if its something in the PR that causes it or its a downstream issue.

**Comment by aureamunoz** [comment]
> @aureamunoz: the downstream check fails, but let me run it against main to see if its something in the PR that causes it or its a downstream issue.

Did you see something?
